Sistema-de-votacion/Controllers/CitizensController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Sistema_de_votacion.Data;
using Sistema_de_votacion.Models;
using Sistema_de_votacion.Services.Citizens;
using Sistema_de_votacion.Services.Elections;

namespace Sistema_de_votacion.Controllers
{
    [Authorize]
    public class CitizensController : Controller
    {
        private readonly ICitizenService _citizenServices;
        private readonly IElectionService _electionService;

        public CitizensController(ICitizenService citizenServices, IElectionService electionService)
        {
            _citizenServices = citizenServices;
            _electionService = electionService;
        }

        // GET: Citizens
        public async Task<IActionResult> Index()
        {
            var citizens = (await _citizenServices.GetCitizenByConditionAsync(c => c.IsActive == true ))
                .OrderBy(c => c.Name).ThenBy(c => c.LastName);
            return View(citizens.ToList());
        }

        [HttpPost]
        public async Task<IActionResult> Index( string activeParam)
        {
            IQueryable<Citizen> citizens;

            if (activeParam == "on") {
                citizens = await _citizenServices.GetCitizenByConditionAsync(c => c.IsActive == true);
            }
            else
            {
                citizens = await _citizenServices.GetCitizenByConditionAsync(c => c.IsActive == false);
            }            

            return View(citizens.ToList());
        }

        // GET: Citizens/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var citizen = await _citizenServices.GetCitizenByIdAsync(id);
                
            if (citizen == null)
            {
                return NotFound();
            }

            return View(citizen);
        }

        // GET: Citizens/Create
        public async Task<IActionResult> Create()
        {
            if (await _electionService.VerifyElectionOpenAsync())
            {
                ViewBag.Message = "No es posible crear o añadir ningun ciudadano porque actualmente existe una eleccion abierta.";
                return RedirectToAction("Index");
            }
            return View("Form");
        }

        // POST: Citizens/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Dni,Name,LastName,Email,IsActive")] Citizen citizen)
        {
            if (ModelState.IsValid)
            {               
                if (await _citizenServices.VerifyExistAsync(citizen.Dni))
                {
                    ViewBag.Message = "Actualmente existe un ciudadano que contiene el mismo numero de identidad.";
                    return View("Form", citizen);
                }
                 var newCitizen = await _citizenServices.InsertCitizenAsync(citizen);
                if (newCitizen != null)
                {
                    return RedirectToAction(nameof(Index));
                }                
                
            }
            return View("Form",citizen);
        }

        // GET: Citizens/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (await _electionService.VerifyElectionOpenAsync())
            {
                ViewBag.Message = "No es posible modificar ningun ciudadano porque actualmente existe una eleccion abierta.";
                return RedirectToAction("Index");
            }
            if (id == null)
            {
                return NotFound();
            }

            var citizen = await _citizenServices.GetCitizenByIdAsync(id);
            if (citizen == null)
            {
                return NotFound();
            }
            return View("Form", citizen);
        }

        // POST: Citizens/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Dni,Name,LastName,Email,IsActive")] Citizen citizen)
        {
            if (id != citizen.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (await _citizenServices.VerifyExistAsync(citizen.Dni))
                    {
                        ViewBag.Message = "Actualmente existe un ciudadano que contiene el mismo numero de identidad.";
                        return View("Form", citizen);
                    }
                    await _citizenServices.UdateCitizenAsync(citizen);
                   
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CitizenExists(citizen.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View("Form", citizen);
        }

        // GET: Citizens/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (await _electionService.VerifyElectionOpenAsync())
            {
                ViewBag.Message = "No es posible eliminar ningun ciudadano porque actualmente existe una eleccion abierta.";
                return RedirectToAction("Index");
            }
            if (id == null)
            {
                return NotFound();
            }

            var citizen = await _citizenServices.GetCitizenByIdAsync(id);
                
            if (citizen == null)
            {
                return NotFound();
            }

            return View(citizen);
        }

        // POST: Citizens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (await _electionService.VerifyElectionOpenAsync())
            {
                ViewBag.Message = "No es posible eliminar ningun ciudadano porque actualmente existe una eleccion abierta.";
                return RedirectToAction("Index");
            }
            var citizen = await _citizenServices.GetCitizenByIdAsync(id);
            if (citizen != null)
            {
                await _citizenServices.DeleteCitizenAsync(citizen);
            }          
          
            return RedirectToAction(nameof(Index));
        }

        private bool CitizenExists(int id)
        {
            var citizen = _citizenServices.GetCitizenByIdAsync(id);
            if (citizen != null)
                return true;
            return false;
        }
    }
}

Sistema-de-votacion/Controllers/PositionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Sistema_de_votacion.Data;
using Sistema_de_votacion.Models;
using Sistema_de_votacion.Services.Candidates.Positions;
using Sistema_de_votacion.Services.Elections;

namespace Sistema_de_votacion.Controllers
{
    [Authorize]
    public class PositionsController : Controller
    {
        private readonly IPositionService _positionService;
        private readonly IElectionService _electionService;

        public PositionsController(IPositionService positionService, IElectionService electionService)
        {
            _positionService = positionService;
            _electionService = electionService;
        }

        // GET: Positions
        public async Task<IActionResult> Index()
        {
            return View(await _positionService.GetPositionsByConditionAsync(p => p.IsActive == true));
        }
        [HttpPost]
        public async Task<IActionResult> Index(string activeParam)
        {
            IEnumerable<Position> positions;

            if (activeParam == "on")            
                positions = await _positionService.GetPositionsByConditionAsync(c => c.IsActive == true);            
            else            
                positions = await _positionService.GetPositionsByConditionAsync(c => c.IsActive == false);            

            return View(positions.ToList());
        }

        // GET: Positions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (await _electionService.VerifyElectionOpenAsync())
            {
                ViewBag.Message="No es posible Modificar ninguna posicion politica porque actualmente existe una eleccion abierta.";
                return RedirectToAction("Index");
            }
            if (id == null)
            {
                return NotFound();
            }

            var position = await _positionService.GetPositionByIdAsync(id.Value);
                
            if (position == null)
            {
                return NotFound();
            }

            return View(position);
        }

        // GET: Positions/Create
        public async Task<IActionResult> Create()
        {
            if (await _electionService.VerifyElectionOpenAsync())
            {
                ViewBag.Message = "No es posible crear o añadir ninguna posicion politica porque actualmente existe una eleccion abierta.";
                return RedirectToAction("Index");
            }
            return View("Form");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description")] Position position)
        {
            if (ModelState.IsValid)
            {
                if (await _positionService.VerifyExistAsync(position.Name))
                {
                    ViewBag.Message = "No es posible añadir la posicion porque actualmente existe un posicion politica activa que contiene el mismo nombre.";
                    return View("Form", position);
                }
                await  _positionService.InsertPositionAsync(position);
               
                return RedirectToAction(nameof(Index));
            }
            return View("Form",position);
        }

        // GET: Positions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var position = await _positionService.GetPositionByIdAsync(id.Value);
            if (position == null)
            {
                return NotFound();
            }
            return View("Form",position);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,IsActive")] Position position)
        {
            if (id != position.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (await _positionService.VerifyExistAsync(position.Name))
                    {
                        ViewBag.Message = "No es posible añadir la posicion porque actualmente existe un posicion politica activa que contiene el mismo nombre.";
                        return View("Form", position);
                    }
                    await _positionService.UdatePositionAsync(position);
                    
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await PositionExists(position.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View("Form",position);
        }

        // GET: Positions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (await _electionService.VerifyElectionOpenAsync())
            {
                ViewBag.Message = "No es posible Eliminar ninguna posicion politica porque actualmente existe una eleccion abierta.";
                return RedirectToAction("Index");
            }
            if (id == null)
            {
                return NotFound();
            }
            var position =  await _positionService.GetPositionByIdAsync(id.Value);
            
                
            if (position == null)
            {
                return NotFound();
            }

            return View(position);
        }

        // POST: Positions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (await _electionService.VerifyElectionOpenAsync())
            {
                ViewBag.Message = "No es posible eliminar ninguna posicion politica porque actualmente existe una eleccion abierta.";
                return RedirectToAction("Index");
            }
            var position = await _positionService.GetPositionByIdAsync(id);
            await  _positionService.DeletePositionAsync(position);
            
            return RedirectToAction(nameof(Index));
        }

        private async  Task<bool> PositionExists(int id)
        {
            return (await _positionService.GetPositionsAsync()).Any(e => e.Id == id);
        }
    }
}

Sistema-de-votacion/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="~/Images/IconoVotar.png" />
    <title>@ViewData["Title"] - Sistema de votacion</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <script src="~/lib/jquery/dist/jquery.js"></script>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="AdminitrationHome" asp-action="Index">
                    <img src="~/Images/IconoVotar.png" width="30" height="30" class="d-inline-block align-top" alt="">
                    Administracion
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Elections" asp-action="ElectionsList">Elecciones</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Candidates" asp-action="Index">Candidatos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="PoliticParties" asp-action="Index">Partidos Politicos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Positions" asp-action="Index">Posiciones Politicas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Citizens" asp-action="Index">Ciudadanos</a>
                        </li>
                        <li class="nav-item ml-lg-auto">
                            <a class="nav-link text-white-50 text-right" asp-area="" asp-controller="Account" asp-action="Logout">@User.Identity.Name | Cerrar Sesion</a>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @if (@ViewBag.Message != null)
            {
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>Advertencia!</strong> @ViewBag.Message
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            }
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - Sistema de votacion 
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Sistema-de-votacion/Views/Shared/_LayoutVotation.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="~/Images/IconoVotar.png" />
    <title>@ViewData["Title"] - Sistema de votacion</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <script src="~/lib/jquery/dist/jquery.js"></script>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Elections" asp-action="Index">
                    <img src="~/Images/IconoVotar.png" width="30" height="30" class="d-inline-block align-top" alt="">
                    Sistema de Votacion
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Administracion</a>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @if (@ViewBag.Message != null)
            {
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>Advertencia!</strong> @ViewBag.Message
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            }
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - Sistema de votacion
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>